### ISSUE TITLE
Support for Case Insensitive Table Names in "table-ordering.txt" File

### ISSUE THREAD

**Issue by bitantepd23** [database-rider/database-rider#130]
When using `@DBUnit` and Spring Boot's H2 database, the provided DataSet can only be initialized if `table-order.txt` has uppercase names in the file. Setting `caseInsensitiveStrategy` equal to `Orthography.UPPERCASE` or `Orthography.LOWERCASE` does not fix the issue; the only remedy is to change the case of the table names in the `table-ordering.txt` file.

I used this as my test case:

    @ExtendWith(SpringExtension.class)
    @DataJpaTest
    @DBRider
    @DBUnit
    @DataSet(value = "datasets/reference/system_user.csv", transactional = true)
    public class H2Test {

	    @Test
	    public void h2CaseSensitiveTableNamesTest() { }

    }

In conjunction with my `table-ordering.txt` file like this:
`system_user`

Stacktrace:

    java.lang.RuntimeException: Could not create dataset for test 'h2CaseSensitiveTableNamesTest'.
    
        at com.github.database.rider.core.RiderRunner.runBeforeTest(RiderRunner.java:48)
        at com.github.database.rider.spring.DBRiderTestExecutionListener.beforeTestMethod(DBRiderTestExecutionListener.java:25)
        at org.springframework.test.context.TestContextManager.beforeTestMethod(TestContextManager.java:291)
        at org.springframework.test.context.junit.jupiter.SpringExtension.beforeEach(SpringExtension.java:107)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeBeforeEachCallbacks$0(TestMethodTestDescriptor.java:130)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeBeforeMethodsOrCallbacksUntilExceptionOccurs(TestMethodTestDescriptor.java:156)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeBeforeEachCallbacks(TestMethodTestDescriptor.java:129)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:108)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:59)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$4(NodeTestTask.java:108)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:98)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:74)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$4(NodeTestTask.java:112)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:98)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:74)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$4(NodeTestTask.java:112)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:98)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:74)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
        at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
        at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:220)
        at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:188)
        at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:202)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:181)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
        at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:69)
        at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
        at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
        at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
    Caused by: com.github.database.rider.core.exception.DataBaseSeedingException: Could not initialize dataset: datasets/reference/system_user.csv
    	at com.github.database.rider.core.dataset.DataSetExecutorImpl.createDataSet(DataSetExecutorImpl.java:164)
    	at com.github.database.rider.core.RiderRunner.runBeforeTest(RiderRunner.java:46)
    	... 37 more
    Caused by: org.dbunit.dataset.DataSetException: Exception while searching the dependent tables.
    	at org.dbunit.database.DatabaseSequenceFilter.sortTableNames(DatabaseSequenceFilter.java:105)
    	at org.dbunit.database.DatabaseSequenceFilter.<init>(DatabaseSequenceFilter.java:67)
    	at com.github.database.rider.core.dataset.DataSetExecutorImpl.performSequenceFiltering(DataSetExecutorImpl.java:278)
    	at com.github.database.rider.core.dataset.DataSetExecutorImpl.createDataSet(DataSetExecutorImpl.java:152)
    	... 38 more
    Caused by: org.dbunit.util.search.SearchException: org.dbunit.dataset.NoSuchTableException: The table 'system_user' does not exist in schema 'null'
    	at org.dbunit.database.search.AbstractMetaDataBasedSearchCallback.getNodes(AbstractMetaDataBasedSearchCallback.java:154)
    	at org.dbunit.database.search.AbstractMetaDataBasedSearchCallback.getNodesFromImportedKeys(AbstractMetaDataBasedSearchCallback.java:99)
    	at org.dbunit.database.search.ImportedKeysSearchCallback.getEdges(ImportedKeysSearchCallback.java:53)
    	at org.dbunit.util.search.DepthFirstSearch.reverseSearch(DepthFirstSearch.java:264)
    	at org.dbunit.util.search.DepthFirstSearch.search(DepthFirstSearch.java:148)
    	at org.dbunit.util.search.DepthFirstSearch.search(DepthFirstSearch.java:104)
    	at org.dbunit.database.search.TablesDependencyHelper.getDependentTables(TablesDependencyHelper.java:92)
    	at org.dbunit.database.search.TablesDependencyHelper.getDependentTables(TablesDependencyHelper.java:73)
    	at org.dbunit.database.DatabaseSequenceFilter.getDependencyInfo(DatabaseSequenceFilter.java:201)
    	at org.dbunit.database.DatabaseSequenceFilter.sortTableNames(DatabaseSequenceFilter.java:101)
    	... 41 more
    Caused by: org.dbunit.dataset.NoSuchTableException: The table 'system_user' does not exist in schema 'null'
    	at org.dbunit.database.search.AbstractMetaDataBasedSearchCallback.getNodes(AbstractMetaDataBasedSearchCallback.java:186)
    	at org.dbunit.database.search.AbstractMetaDataBasedSearchCallback.getNodes(AbstractMetaDataBasedSearchCallback.java:149)
    	... 50 more

When I change the case to `SYSTEM_USER`, the test passes with no issues.

**Comment by rmpestano** [comment]
Hi there, 

H2 always create tables in uppercase so I think it is expected behaviour.

Also note that the `caseInsensitiveStrategy` will only take effect if `caseSensitiveTableNames` is true, see [dbunit configuration here](https://github.com/database-rider/database-rider#configuration).

See [Postgres tests here](https://github.com/database-rider/database-rider/blob/master/rider-core/src/test/java/com/github/database/rider/core/PostgreSQLDatabaseIt.java) for an example of caseSensitive tables. 

I hope it helps.

**Comment by rmpestano** [comment]
Also if you're using JPA to create tables you need to specify lowercase table name using quotes, [see here](https://github.com/database-rider/database-rider/blob/21d5043e08b18a594a659e2508014fa9fba77fab/rider-core/src/test/java/com/github/database/rider/core/model/lowercase/User.java#L8).
