### ISSUE TITLE
Disabling constraints does not appear to work with oracle

### ISSUE THREAD

**Issue by solidjb** [database-rider/database-rider#15]
When I attempt to disable constraints with an oracle database i get the following exception:

```
Caused by: java.sql.SQLSyntaxErrorException: ORA-00911: invalid character

	at oracle.jdbc.driver.SQLStateMapping.newSQLException(SQLStateMapping.java:91)
	at oracle.jdbc.driver.DatabaseError.newSQLException(DatabaseError.java:133)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:206)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:455)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:413)
	at oracle.jdbc.driver.T4C8Oall.receive(T4C8Oall.java:1035)
	at oracle.jdbc.driver.T4CStatement.doOall8(T4CStatement.java:183)
	at oracle.jdbc.driver.T4CStatement.executeForRows(T4CStatement.java:942)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1223)
	at oracle.jdbc.driver.OracleStatement.executeInternal(OracleStatement.java:1775)
	at oracle.jdbc.driver.OracleStatement.execute(OracleStatement.java:1744)
	at oracle.jdbc.driver.OracleStatementWrapper.execute(OracleStatementWrapper.java:299)
	at com.github.database.rider.core.dataset.DataSetExecutorImpl.disableConstraints(DataSetExecutorImpl.java:296)
	at com.github.database.rider.core.dataset.DataSetExecutorImpl.createDataSet(DataSetExecutorImpl.java:136)
	... 27 more
```

The line in question is this:

```java
connectionHolder.getConnection().createStatement().execute("SET CONSTRAINTS ALL DEFERRED;");
```

When I google how to disable constraints for oracle, that is not what it describes, nor is it what unitils did.   (https://github.com/arteam/unitils/blob/master/unitils-core/src/main/java/org/unitils/core/dbsupport/OracleDbSupport.java)

```java
public void disableReferentialConstraints() {
        Connection connection = null;
        Statement queryStatement = null;
        Statement alterStatement = null;
        ResultSet resultSet = null;
        try {
            connection = getSQLHandler().getDataSource().getConnection();
            queryStatement = connection.createStatement();
            alterStatement = connection.createStatement();

            // to be sure no recycled items are handled, all items with a name that starts with BIN$ will be filtered out.
            resultSet = queryStatement.executeQuery("select TABLE_NAME, CONSTRAINT_NAME from ALL_CONSTRAINTS where CONSTRAINT_TYPE = 'R' and OWNER = '" + getSchemaName() + "' and CONSTRAINT_NAME not like 'BIN$%' and STATUS <> 'DISABLED'");
            while (resultSet.next()) {
                String tableName = resultSet.getString("TABLE_NAME");
                String constraintName = resultSet.getString("CONSTRAINT_NAME");
                alterStatement.executeUpdate("alter table " + qualified(tableName) + " disable constraint " + quoted(constraintName));
            }
        } catch (Exception e) {
            throw new UnitilsException("Error while disabling referential constraints on schema " + getSchemaName(), e);
        } finally {
            closeQuietly(queryStatement);
            closeQuietly(connection, alterStatement, resultSet);
        }
    }
```

I did not see any tests in the project for verifying that this works with oracle, but I could have missed them.  Has the constraint functionality been tested against oracle?  We are using some version of oracle 11.

**Comment by rmpestano** [comment]
Hi @solidjb,

> Has the constraint functionality been tested against oracle?

The tests are run against in-memory db only, that's why we didn't catch this bug before. I think HSQLDB can emulate Oracle dialect, maybe we can try that to simplify tests. 

Would you like to provide a PR? otherwise I can look at it over the weekend. 

Thanks for the feedback.

**Comment by rmpestano** [comment]
Hi @solidjb,

can you test with latest [snapshot](https://github.com/database-rider/database-rider#snapshots)? RC3-SNAPSHOT

If you find any issues feel free to reopen this issue.

**Comment by solidjb** [comment]
Sorry.  Priorities got switched around at work, and had to move on.  Will try to squeeze out time soon.
