### ISSUE TITLE
ExportDataSet can not to establish connection

### ISSUE THREAD

**Issue by artemy-osipov** [database-rider/database-rider#19]
If test only export dataset via annotation then connection can not be established.

Minimal test case to reproduce:
```java
@RunWith(JUnit4.class)
public class SingleExportDataSetIt {

    @Rule
    public EntityManagerProvider emProvider = EntityManagerProvider.instance("rules-it");

    @Rule
    public DBUnitRule dbUnitRule = DBUnitRule.instance(emProvider.connection());

    @Test
    @ExportDataSet(format = DataSetFormat.YML, outputName = "target/exported/yml/singleExport.yml")
    public void shouldExportData() {
    }

    @AfterClass
    public static void assertGeneratedDataSets() {
        File export = new File("target/exported/yml/singleExport.yml");
        assertThat(export).exists();
    }
}
```

```
java.lang.RuntimeException: Provide a valid connection to export datasets
	at com.github.database.rider.core.exporter.DataSetExporter.export(DataSetExporter.java:68) ~[rider-core-1.0.0.jar:na]
	at com.github.database.rider.core.DBUnitRule.exportDataSet(DBUnitRule.java:221) [rider-core-1.0.0.jar:na]
	at com.github.database.rider.core.DBUnitRule.access$500(DBUnitRule.java:37) [rider-core-1.0.0.jar:na]
	at com.github.database.rider.core.DBUnitRule$1.evaluate(DBUnitRule.java:184) [rider-core-1.0.0.jar:na]
	at org.junit.rules.RunRules.evaluate(RunRules.java:20) [junit-4.12.jar:4.12]
```

**Comment by rmpestano** [comment]
fixed for 1.0.1
