### ISSUE TITLE
NullPointerException when expectedValue is `regex`

### ISSUE THREAD

**Issue by iakunin** [database-rider/database-rider#206]
The problem occurs when matching `null` actual value against expected `regex` value.

NullPointerException is thrown [here](https://github.com/database-rider/database-rider/blob/master/rider-core/src/main/java/com/github/database/rider/core/assertion/DataSetAssert.java#L76) (`actualValue.toString()`) with following stacktrace:

```
java.lang.NullPointerException
	at com.github.database.rider.core.assertion.DataSetAssert.compareData(DataSetAssert.java:76)
	at org.dbunit.assertion.DbUnitAssert.assertEquals(DbUnitAssert.java:409)
	at org.dbunit.assertion.DbUnitAssert.assertEquals(DbUnitAssert.java:312)
	at org.dbunit.assertion.DbUnitAssert.assertEquals(DbUnitAssert.java:274)
	at org.dbunit.assertion.DbUnitAssert.assertEqualsIgnoreCols(DbUnitAssert.java:122)
	at com.github.database.rider.core.assertion.DataSetAssertion.assertEqualsIgnoreCols(DataSetAssertion.java:18)
	at com.github.database.rider.core.dataset.DataSetExecutorImpl.compareCurrentDataSetWith(DataSetExecutorImpl.java:1014)
	at com.github.database.rider.core.RiderRunner.performDataSetComparison(RiderRunner.java:147)
	at com.github.database.rider.core.RiderRunner.runAfterTest(RiderRunner.java:64)
	at com.github.database.rider.spring.DBRiderTestExecutionListener.afterTestMethod(DBRiderTestExecutionListener.java:34)
	at org.springframework.test.context.TestContextManager.afterTestMethod(TestContextManager.java:441)
	at org.springframework.test.context.junit.jupiter.SpringExtension.afterEach(SpringExtension.java:140)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeAfterEachCallbacks$11(TestMethodTestDescriptor.java:245)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeAllAfterMethodsOrCallbacks$12(TestMethodTestDescriptor.java:256)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeAllAfterMethodsOrCallbacks$13(TestMethodTestDescriptor.java:256)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeAllAfterMethodsOrCallbacks(TestMethodTestDescriptor.java:255)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeAfterEachCallbacks(TestMethodTestDescriptor.java:244)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:141)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:69)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:135)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:229)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:197)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:211)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:191)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)
```

It would be better to handle this case in a more correct way and show more user-friendly error.

**Comment by rmpestano** [comment]
Hi @iakunin,

can you try with `1.13.1-SNAPSHOT`? to do that you'll need to [enable snapshots](https://github.com/database-rider/database-rider#snapshots) on your build system. 

Thank you for the feedback!

**Comment by iakunin** [comment]
@rmpestano now it works just perfect!

Here is user-friendly error I've got:
```
 junit.framework.ComparisonFailure: value (table=xxx, row=1, col=yyy) expected:<[regex:^\d{4}$]> but was:<[null]>
```

Many thanks for your rapid reaction at my bug-report!

**Comment by rmpestano** [comment]
Glad to hear that! 

`v1.13.1` should be on maven central in a few hours

**Comment by iakunin** [comment]
Unbelievable speed! :)

**Comment by iakunin** [comment]
@rmpestano 

> v1.13.1 should be on maven central in a few hours

Unfortunately, cannot see it [there](https://mvnrepository.com/artifact/com.github.database-rider/rider-core). There is only [`1.13.0`](https://mvnrepository.com/artifact/com.github.database-rider/rider-core/1.13.0). 

Should I be more patient maybe? :)

**Comment by rmpestano** [comment]
Hi @iakunin, it's already on central, since yesterday: https://search.maven.org/search?q=database-rider

**Comment by iakunin** [comment]
@rmpestano seems that web-view of mvnrepository.com has some indexes. I'll try to update db-rider in my project. Thank you for your response!
