### ISSUE TITLE
ExpectedDataSet can not find table when yaml format is using

### ISSUE THREAD

**Issue by artemy-osipov** [database-rider/database-rider#21]
If database has case sensitive table names then ExpectedDataSet cannot find them when table has lowercase name and yaml format is using.

For example if database has name "table_name_written_lowercase" and such test was written
```
@Test
@ExpectedDataSet("table_name_written_lowercase.yml")
@DBUnit(caseSensitiveTableNames = true)
public void insert() throws Exception {
    ...insert logic
}
```
with
```
table_name_written_lowercase:
  - id: 1
    property: "value"
```
then error occurs
```
Caused by: org.dbunit.dataset.NoSuchTableException: Did not find table 'TABLE_NAME_WRITTEN_LOWERCASE' in schema 'null'
	at org.dbunit.database.DatabaseTableMetaData.<init>(DatabaseTableMetaData.java:146)
	at org.dbunit.database.DatabaseDataSet.getTableMetaData(DatabaseDataSet.java:316)
	at org.dbunit.database.DatabaseDataSet.getTable(DatabaseDataSet.java:333)
	at com.github.database.rider.core.dataset.DataSetExecutorImpl.compareCurrentDataSetWith(DataSetExecutorImpl.java:693)
	... 27 more
```

**Comment by rmpestano** [comment]
Hi @artemy-osipov, my idea is to release 1.1.0 soon, anything else you want to include in this release?

It will not be a minor release because it breaks tests that were using HSQLDB and lowercase table/column names in datasets.

Can we close this one, right?

**Comment by artemy-osipov** [comment]
@rmpestano, yes, I think that all the issues that I met.
PS thanks for the library

**Comment by rmpestano** [comment]
Thank you for the contributions!
