### ISSUE TITLE
Quarkus >=1.3.0.Final Not Supported

### ISSUE THREAD

**Issue by jsendlewski** [database-rider/database-rider#233]
Hi!

It seems that Quarkus starting from version 1.3.0.Final is not supported. There seems to be a missing dependency on `com.bea.xml.stream.MXParserFactory`. 
Quarkus versions < 1.3.0.Final are working fine.

Please see the following:

```
java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.narayana.jta.deployment.NarayanaJtaProcessor#build threw an exception: javax.xml.stream.FactoryConfigurationError: Provider com.bea.xml.stream.MXParserFactory not found
	at javax.xml.stream.FactoryFinder.newInstance(FactoryFinder.java:72)
	at javax.xml.stream.FactoryFinder.find(FactoryFinder.java:178)
	at javax.xml.stream.FactoryFinder.find(FactoryFinder.java:92)
	at javax.xml.stream.XMLInputFactory.newInstance(XMLInputFactory.java:136)
	at com.arjuna.common.util.propertyservice.PropertiesFactoryStax.loadFromXML(PropertiesFactoryStax.java:46)
	at com.arjuna.common.util.propertyservice.AbstractPropertiesFactory.loadFromFile(AbstractPropertiesFactory.java:149)
	at com.arjuna.common.util.propertyservice.AbstractPropertiesFactory.getPropertiesFromFile(AbstractPropertiesFactory.java:102)
	at com.arjuna.common.util.propertyservice.AbstractPropertiesFactory.initDefaultProperties(AbstractPropertiesFactory.java:195)
	at com.arjuna.common.util.propertyservice.AbstractPropertiesFactory.getDefaultProperties(AbstractPropertiesFactory.java:62)
	at com.arjuna.common.util.propertyservice.PropertiesFactory.getDefaultProperties(PropertiesFactory.java:48)
	at io.quarkus.narayana.jta.deployment.NarayanaJtaProcessor.build(NarayanaJtaProcessor.java:85)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:938)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:273)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2027)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1551)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1442)
	at java.base/java.lang.Thread.run(Thread.java:834)
	at org.jboss.threads.JBossThread.run(JBossThread.java:479)
```

Cheers!

**Comment by rmpestano** [comment]
Hi @jsendlewski, you need to exclude `stax-api` from[ rider-cdi dependency](https://github.com/database-rider/database-rider/commit/fe89346f6e2682f9dd5338525e313fdacef6dd6e):

```
           <artifactId>rider-cdi</artifactId>
            <version>${project.version}</version>	            
            <scope>test</scope>	        
            <exclusions>
                <exclusion>
                    <groupId>stax</groupId>
                    <artifactId>stax-api</artifactId>
                </exclusion>
            </exclusions>
```

This dependency is brought by dbunit so I don't think we can do anything from dbrider side.

Can you try that?

**Comment by jsendlewski** [comment]
Hi @rmpestano,

Apologies for a late reply. I've managed to test the exclusion and it works like magic. 

Thank you for your support!

**Comment by rmpestano** [comment]
That's great, thank you for the feedback!
