### ISSUE TITLE
Regex doesn't work due to DataSetAssert's compareData method isn't called

### ISSUE THREAD

**Issue by jorge-pascual** [database-rider/database-rider#250]
Hello all!

I'm trying to use Regex in my code but I can't. 

It looks like `DataSetAssert` isn't used by the system. So, the regex engine is never called. 

This is the stacktrace where you can see that the `compareData` methods used are from `DbUnitAssertBase` and not from `DataSetAssert`

```
junit.framework.ComparisonFailure: value (table=platform.accounting_accounts_suppliers, row=0, col=id) expected:<[regex:^[0-9a-f]{8}-[0-9a-f]{4}-[0-5][0-9a-f]{3}-[089ab][0-9a-f]{3}-[0-9a-f]{12}$]> but was:<[074a2bef-08a6-4137-9f08-c3a30aceba9d]>
	at org.dbunit.assertion.JUnitFailureFactory.createFailure(JUnitFailureFactory.java:39)
	at org.dbunit.assertion.DefaultFailureHandler.createFailure(DefaultFailureHandler.java:105)
	at org.dbunit.assertion.DefaultFailureHandler.handle(DefaultFailureHandler.java:240)
	at org.dbunit.assertion.DbUnitAssertBase.failIfNecessary(DbUnitAssertBase.java:619)
	at org.dbunit.assertion.DbUnitAssertBase.compareData(DbUnitAssertBase.java:602)
	at org.dbunit.assertion.DbUnitAssertBase.compareData(DbUnitAssertBase.java:561)
	at org.dbunit.assertion.DbUnitAssertBase.assertWithValueComparer(DbUnitAssertBase.java:439)
	at org.dbunit.assertion.DbUnitAssert.assertEquals(DbUnitAssert.java:300)
	at org.dbunit.assertion.DbUnitAssert.assertEquals(DbUnitAssert.java:268)
	at org.dbunit.assertion.DbUnitAssert.assertEquals(DbUnitAssert.java:227)
	at org.dbunit.assertion.DbUnitAssert.assertEqualsIgnoreCols(DbUnitAssert.java:103)
	at com.github.database.rider.core.assertion.DataSetAssertion.assertEqualsIgnoreCols(DataSetAssertion.java:18)
	at com.github.database.rider.core.dataset.DataSetExecutorImpl.compareCurrentDataSetWith(DataSetExecutorImpl.java:1035)
	at com.github.database.rider.core.dataset.DataSetExecutorImpl.compareCurrentDataSetWith(DataSetExecutorImpl.java:1062)
```

Any suggestion?

thank you!

**Comment by rmpestano** [comment]
Hi, do you have any code to share? Which version are you using?

Also, [here](https://github.com/database-rider/database-rider/blob/cea65b6fe20733b07b49e73bed7b887ce8dfa626/rider-core/src/test/java/com/github/database/rider/core/ExpectedDataSetIt.java#L72-L84) and [here](https://github.com/database-rider/database-rider/blob/cea65b6fe20733b07b49e73bed7b887ce8dfa626/rider-core/src/test/java/com/github/database/rider/core/ExpectedDataSetIt.java#L213-L221) you can find working examples.

**Comment by jorge-pascual** [comment]
Sure... I've uploaded a sample project here: https://github.com/jorge-pascual/test-rider-regex

Stack:
- Spring Boot 2.4.0
- Postgresql 42.2.12
- Cucumber 6.0.0
- DBUnit 2.6.0
- Rider 1.18.0

```
dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation "org.postgresql:postgresql:42.2.12"
    implementation 'com.vladmihalcea:hibernate-types-52:2.9.11'

    compileOnly 'org.projectlombok:lombok:1.18.12'
    testCompileOnly 'org.projectlombok:lombok:1.18.12'
    annotationProcessor 'org.projectlombok:lombok:1.18.12'

    testImplementation 'io.cucumber:cucumber-java:6.0.0'
    testImplementation 'io.cucumber:cucumber-junit:6.0.0'
    testImplementation 'io.cucumber:cucumber-spring:6.0.0'
    testImplementation 'net.masterthought:cucumber-reporting:4.2.3' // For reporting purposes

    testImplementation 'org.dbunit:dbunit:2.6.0'
    testImplementation 'com.github.database-rider:rider-junit5:1.18.0'
    testImplementation 'com.github.database-rider:rider-cucumber:1.18.0'


    testImplementation 'org.springframework.boot:spring-boot-starter-test'

}
```

Service:
```
@Service
public class TestService {

    @Autowired
    private TestRepository testRepository;

    public void saveItems() {
        testRepository.save(new TestEntity("Test 1"));
        testRepository.save(new TestEntity("Test 2"));
        testRepository.save(new TestEntity("Test 3"));
    }

}
```

Stepdefs:

```
public class Stepdefs {

    @Autowired
    private TestService testService;

    @PersistenceContext
    private EntityManager em;

    @Given("A few records")
    public void aFewRecords() {
        testService.saveItems();
    }

    @When("we test them against a regex dataset")
    public void weTestThemAgainstARegexDataset() {
    }

    @Then("we expect it works")
    @Transactional
    public void weExpectItWorks() {

        Session hibernateSession = em.unwrap(Session.class);
        hibernateSession.doWork(connection -> {
            DataSetExecutor dbunitExecutor = DataSetExecutorImpl.instance(new ConnectionHolderImpl(connection));
            try {
                dbunitExecutor
                    .compareCurrentDataSetWith(
                        new DataSetConfig("database/result.yml"),
                        new String[] {},
                        null,
                            new String[] {}
                );
            } catch (DatabaseUnitException e) {
                e.printStackTrace();
            }
        });
    }
}
```

And Dataset:
```
test.test_entity:
  - id: "regex:^[0-9a-f]{8}-[0-9a-f]{4}-[0-5][0-9a-f]{3}-[089ab][0-9a-f]{3}-[0-9a-f]{12}$"
    name: "Test 1"

  - id: "regex:^[0-9a-f]{8}-[0-9a-f]{4}-[0-5][0-9a-f]{3}-[089ab][0-9a-f]{3}-[0-9a-f]{12}$"
    name: "Test 2"

  - id: "regex:^[0-9a-f]{8}-[0-9a-f]{4}-[0-5][0-9a-f]{3}-[089ab][0-9a-f]{3}-[0-9a-f]{12}$"
    name: "Test 3"
```

Error:
```
Step failed
junit.framework.ComparisonFailure: value (table=test.test_entity, row=0, col=id) expected:<[regex:^[0-9a-f]{8}-[0-9a-f]{4}-[0-5][0-9a-f]{3}-[089ab][0-9a-f]{3}-[0-9a-f]{12}$]> but was:<[ee5beecc-8ea2-426a-b2d8-6fd2d6c188a0]>
	at org.dbunit.assertion.JUnitFailureFactory.createFailure(JUnitFailureFactory.java:39)
	at org.dbunit.assertion.DefaultFailureHandler.createFailure(DefaultFailureHandler.java:105)
	at org.dbunit.assertion.DefaultFailureHandler.handle(DefaultFailureHandler.java:240)
	at org.dbunit.assertion.DbUnitAssertBase.failIfNecessary(DbUnitAssertBase.java:619)
	at org.dbunit.assertion.DbUnitAssertBase.compareData(DbUnitAssertBase.java:602)
	at org.dbunit.assertion.DbUnitAssertBase.compareData(DbUnitAssertBase.java:561)
	at org.dbunit.assertion.DbUnitAssertBase.assertWithValueComparer(DbUnitAssertBase.java:439)
	at org.dbunit.assertion.DbUnitAssert.assertEquals(DbUnitAssert.java:300)
	at org.dbunit.assertion.DbUnitAssert.assertEquals(DbUnitAssert.java:268)
	at org.dbunit.assertion.DbUnitAssert.assertEquals(DbUnitAssert.java:227)
	at org.dbunit.assertion.DbUnitAssert.assertEqualsIgnoreCols(DbUnitAssert.java:103)
	at com.github.database.rider.core.assertion.DataSetAssertion.assertEqualsIgnoreCols(DataSetAssertion.java:18)
	at com.github.database.rider.core.dataset.DataSetExecutorImpl.compareCurrentDataSetWith(DataSetExecutorImpl.java:1035)
	at com.github.database.rider.core.dataset.DataSetExecutorImpl.compareCurrentDataSetWith(DataSetExecutorImpl.java:1062)
	at com.example.demo.glue.Stepdefs.lambda$weExpectItWorks$0(Stepdefs.java:45)
	at org.hibernate.jdbc.WorkExecutor.executeWork(WorkExecutor.java:37)
	at org.hibernate.internal.AbstractSharedSessionContract.lambda$doWork$1(AbstractSharedSessionContract.java:1068)
	at org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl.coordinateWork(JdbcCoordinatorImpl.java:306)
	at org.hibernate.internal.AbstractSharedSessionContract.doWork(AbstractSharedSessionContract.java:1084)
	at org.hibernate.internal.AbstractSharedSessionContract.doWork(AbstractSharedSessionContract.java:1071)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.springframework.orm.jpa.SharedEntityManagerCreator$SharedEntityManagerInvocationHandler.invoke(SharedEntityManagerCreator.java:311)
	at com.sun.proxy.$Proxy89.doWork(Unknown Source)
	at com.example.demo.glue.Stepdefs.weExpectItWorks(Stepdefs.java:41)
```

Thank you @rmpestano

**Comment by rmpestano** [comment]
Can you try using RiderDSL like in [this example] (https://github.com/database-rider/database-rider/blob/585beff0ac49c9d71b9eb1fc119c0aeba9bbeeef/rider-core/src/test/java/com/github/database/rider/core/dsl/RiderDSLIt.java#L359)?

**Comment by jorge-pascual** [comment]
Sure @rmpestano 

[I've done it](https://github.com/jorge-pascual/test-rider-regex/blob/40773ecf3c1cde87eebf98789a9e98c153da17f1/src/test/java/com/example/demo/glue/Stepdefs.java#L47). Also I've used `CONTAINS`...  but same result :(


```
Step failed
junit.framework.ComparisonFailure: value (table=test.test_entity, row=0, col=id) expected:<[regex:^[0-9a-f]{8}-[0-9a-f]{4}-[0-5][0-9a-f]{3}-[089ab][0-9a-f]{3}-[0-9a-f]{12}$]> but was:<[ec8f8310-07d4-4edc-862d-469b2b5efe57]>
	at org.dbunit.assertion.JUnitFailureFactory.createFailure(JUnitFailureFactory.java:39)
	at org.dbunit.assertion.DefaultFailureHandler.createFailure(DefaultFailureHandler.java:105)
	at org.dbunit.assertion.DefaultFailureHandler.handle(DefaultFailureHandler.java:240)
	at org.dbunit.assertion.DbUnitAssertBase.failIfNecessary(DbUnitAssertBase.java:619)
	at org.dbunit.assertion.DbUnitAssertBase.compareData(DbUnitAssertBase.java:602)
	at org.dbunit.assertion.DbUnitAssertBase.compareData(DbUnitAssertBase.java:561)
	at org.dbunit.assertion.DbUnitAssertBase.assertWithValueComparer(DbUnitAssertBase.java:439)
	at org.dbunit.assertion.DbUnitAssert.assertEquals(DbUnitAssert.java:300)
	at org.dbunit.assertion.DbUnitAssert.assertEquals(DbUnitAssert.java:268)
	at org.dbunit.assertion.DbUnitAssert.assertEquals(DbUnitAssert.java:227)
	at org.dbunit.assertion.DbUnitAssert.assertEqualsIgnoreCols(DbUnitAssert.java:103)
	at com.github.database.rider.core.assertion.DataSetAssertion.assertEqualsIgnoreCols(DataSetAssertion.java:18)
	at com.github.database.rider.core.dataset.DataSetExecutorImpl.compareCurrentDataSetWith(DataSetExecutorImpl.java:1035)
	at com.github.database.rider.core.dsl.RiderDSL.expectDataSet(RiderDSL.java:53)
	at com.github.database.rider.core.dsl.RiderDSL$DBUnitConfigDSL.expectDataSet(RiderDSL.java:158)
	at com.example.demo.glue.Stepdefs.lambda$weExpectItWorks$0(Stepdefs.java:49)
	at org.hibernate.jdbc.WorkExecutor.executeWork(WorkExecutor.java:37)
	at org.hibernate.internal.AbstractSharedSessionContract.lambda$doWork$1(AbstractSharedSessionContract.java:1068)
	at org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl.coordinateWork(JdbcCoordinatorImpl.java:306)
	at org.hibernate.internal.AbstractSharedSessionContract.doWork(AbstractSharedSessionContract.java:1084)
	at org.hibernate.internal.AbstractSharedSessionContract.doWork(AbstractSharedSessionContract.java:1071)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.springframework.orm.jpa.SharedEntityManagerCreator$SharedEntityManagerInvocationHandler.invoke(SharedEntityManagerCreator.java:311)
	at com.sun.proxy.$Proxy89.doWork(Unknown Source)
	at com.example.demo.glue.Stepdefs.weExpectItWorks(Stepdefs.java:45)
```


It looks like the signature of `DataSetAssert.compareData` is never used. 

`DbUnitAssertBase.assertWithValueComparer` uses

```
compareData(final ITable expectedTable,
            final ITable actualTable, final ComparisonColumn[] comparisonCols,
            final FailureHandler failureHandler,
            final ValueComparer defaultValueComparer,
            final Map<String, ValueComparer> columnValueComparers);
```

and that one, uses 

```
compareData(final ITable expectedTable,
            final ITable actualTable, final ComparisonColumn[] comparisonCols,
            final FailureHandler failureHandler,
            final ValueComparer defaultValueComparer,
            final Map<String, ValueComparer> columnValueComparers,
            final int rowNum, final int columnNum)
```

but no one uses the one with the `DataSetAssert` signature:

```
compareData(ITable expectedTable, 
            ITable actualTable, ComparisonColumn[] comparisonCols, 
            FailureHandler failureHandler)
```

Could it be a problem with the DBUnit version? May be they have changed these methods and `DataSetAssert` is not updated accordingly...

Thanks!

**Comment by rmpestano** [comment]
> Could it be a problem with the DBUnit version? 
Alright, that's for sure the issue, see here:
https://github.com/database-rider/database-rider/issues/111#issuecomment-452425777

I'll try to spend some time on that issue in next weekend

**Comment by jorge-pascual** [comment]
Great! Thanks @rmpestano If I can help in some way... just let me know!

**Comment by jorge-pascual** [comment]
Tested... I've only changed 

```
    testImplementation 'org.dbunit:dbunit:2.6.0'
    testImplementation 'com.github.database-rider:rider-junit5:1.18.0'
    testImplementation 'com.github.database-rider:rider-cucumber:1.18.0'
```

with

```
    testImplementation 'org.dbunit:dbunit:2.5.4'
    testImplementation 'com.github.database-rider:rider-junit5:1.18.0'
    testImplementation 'com.github.database-rider:rider-cucumber:1.18.0'
```

and the same test worked like a charm!.

**Comment by rmpestano** [comment]
Awesome!

**Comment by rmpestano** [comment]
Since `v1.19.0` it should also work with DBunit 2.6.0.
