### ISSUE TITLE
DataBaseSeedingException after migrating from rider-core:1.0.0 to 1.1.0

### ISSUE THREAD

**Issue by jenskreidler** [database-rider/database-rider#26]
Hi, 

when upgrading from 1.0.0 to 1.1.0 I get a DataBaseSeedingException related to case-sensitive table-names.
I checked the DbunitConfig instance rider's read, but the property caseSensitiveTableNames is imho correctly set to false.
In the seeding yaml-file "Mytable" is declared, in the create-ddl MYTABLE is used. In version 1.0.0 and dbunit-rules:0.15.1 everything worked well.

TRACE:
[...]
Caused by: com.github.database.rider.core.exception.DataBaseSeedingException: Could not initialize dataset: a.yml,b.yml,c.yml
	at com.github.database.rider.core.dataset.DataSetExecutorImpl.createDataSet(DataSetExecutorImpl.java:173)
	at com.github.database.rider.core.DBUnitRule$1.evaluate(DBUnitRule.java:95)
	... 20 more
Caused by: org.dbunit.dataset.DataSetException: Exception while searching the dependent tables.
	at org.dbunit.database.DatabaseSequenceFilter.sortTableNames(DatabaseSequenceFilter.java:105)
	at org.dbunit.database.DatabaseSequenceFilter.<init>(DatabaseSequenceFilter.java:67)
	at com.github.database.rider.core.dataset.DataSetExecutorImpl.performSequenceFiltering(DataSetExecutorImpl.java:251)
	at com.github.database.rider.core.dataset.DataSetExecutorImpl.createDataSet(DataSetExecutorImpl.java:161)
	... 21 more
Caused by: org.dbunit.util.search.SearchException: org.dbunit.dataset.NoSuchTableException: The table 'Datatype' does not exist in schema 'null'
	at org.dbunit.database.search.AbstractMetaDataBasedSearchCallback.getNodes(AbstractMetaDataBasedSearchCallback.java:154)
	at org.dbunit.database.search.AbstractMetaDataBasedSearchCallback.getNodesFromImportedKeys(AbstractMetaDataBasedSearchCallback.java:99)
	at org.dbunit.database.search.ImportedKeysSearchCallback.getEdges(ImportedKeysSearchCallback.java:53)
	at org.dbunit.util.search.DepthFirstSearch.reverseSearch(DepthFirstSearch.java:264)
	at org.dbunit.util.search.DepthFirstSearch.search(DepthFirstSearch.java:148)
	at org.dbunit.util.search.DepthFirstSearch.search(DepthFirstSearch.java:104)
	at org.dbunit.database.search.TablesDependencyHelper.getDependentTables(TablesDependencyHelper.java:92)
	at org.dbunit.database.search.TablesDependencyHelper.getDependentTables(TablesDependencyHelper.java:73)
	at org.dbunit.database.DatabaseSequenceFilter.getDependencyInfo(DatabaseSequenceFilter.java:201)
	at org.dbunit.database.DatabaseSequenceFilter.sortTableNames(DatabaseSequenceFilter.java:101)
	... 24 more
Caused by: org.dbunit.dataset.NoSuchTableException: The table 'Mytable' does not exist in schema 'null'
	at org.dbunit.database.search.AbstractMetaDataBasedSearchCallback.getNodes(AbstractMetaDataBasedSearchCallback.java:186)
	at org.dbunit.database.search.AbstractMetaDataBasedSearchCallback.getNodes(AbstractMetaDataBasedSearchCallback.java:149)
	... 33 more

**Comment by rmpestano** [comment]
Hi @jenskreidler,

yes there was a change in how we deal with table names, before 1.1.0 table names were case **In**sensitive (we always set them to upper) but from 1.1.0 its case sensitive. Have you seen migration "guide" [here in release notes](https://github.com/database-rider/database-rider/releases/tag/1.1.0)?

**Comment by jenskreidler** [comment]
Hi Raphael,

thank you for your answer. The release notes quote "If you use HSQLDB and declare your datasets table and column names in lowercase then you must change it to upper **or** use **caseSensitiveTableNames** DBUnit property".

I am using HSQLDB, so why does the option "caseSensitiveTableNames=false" have no effect? I'd expect rider/dbunit to bypass this ignoring case-sensitiv table names or am I wrong?

**Comment by rmpestano** [comment]
"why caseSensitiveTableNames=false have no effect?" false is the default value, the problem is that hsqldb creates the tables in upper case by default. So if your table names are in uppercase on your datasets you should be ok. 

Do you have any sample project to share so I can reproduce your issue?

**Comment by jenskreidler** [comment]
Hi Rafael,thank you for your support. I can verify that the problem is void if I use upper-case table names in yaml seed files. But I have to write upper case column names as well, otherwise an exception rises "null value not allowed for column "ID" for example).
Without digging deeper in the sources, why did this behaviour for hsqldb occur from 1.0.0 to 1.1.0? I mean, neither the dbunit nor the hsqldb version has changed but rider complains about table/column names case-sensitivity after migration.
Nevertheless, thanks for the project, I really enjoy it and it leverages integration testing to a convenient sphere using yaml.
 

    Rafael M. Pestano <notifications@github.com> schrieb am 20:59 Mittwoch, 31.Mai 2017:
 

 "why caseSensitiveTableNames=false have no effect?" false is the default value, the problem is that hsqldb creates the tables in upper case by default. So if your table names are in uppercase on your datasets you should be ok.Do you have any sample project to share so I can reproduce your issue?—

**Comment by rmpestano** [comment]
Hi @jenskreidler,

the behaviour in 1.0.0 was to always make table names to upper([db rider forced](https://github.com/database-rider/database-rider/pull/22/commits/784e20f89b605735ec082197e6117a7b7b1385e6)) and this prevent case sensitive table names no matter you use dbunit caseSensitiveTableNames property. The full discussion about this can be [found in this pr](https://github.com/database-rider/database-rider/pull/22). 

Glad it worked for you and it is helping your it tests ;).

**Comment by jenskreidler** [comment]
OK, understood, thanks. It would be fool-proof to udpdate the changelog by not stating 

> If you use HSQLDB and declare your datasets table and column names in lowercase then you must change it to upper or use caseSensitiveTableNames DBUnit property

Because the last part of the sentence says ("or change ..."), that users should use the DBUnit property and everything works

**Comment by rmpestano** [comment]
For us there is clearly two options and there is even tests showing that, e.g all db rider tests declare datasets in upper and don't use caseSensitive properties but there is an example which uses it and they are linked in the release notes. If that's not correct please tell us.

**Comment by rmpestano** [comment]
refs #32
