### ISSUE TITLE
Cannot read `columnSensing` config from dbunit.yml

### ISSUE THREAD

**Issue by entireboy** [database-rider/database-rider#379]
Hi.
When I add `columnSensing` DBUnit config to *dbunit.yml* file, I can meet an error message like this:

```
Cannot create property=columnSensing for JavaBean=com.github.database.rider.core.configuration.DBUnitConfig@2b8a99eb
 in 'reader', line 1, column 1:
    cacheConnection: false
    ^
Unable to find property 'columnSensing' on class: com.github.database.rider.core.configuration.DBUnitConfig
 in 'reader', line 10, column 16:
    columnSensing: true
                   ^


	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:312)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.construct(Constructor.java:189)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.construct(Constructor.java:345)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:182)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:141)
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:127)
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:450)
	at org.yaml.snakeyaml.Yaml.loadAs(Yaml.java:444)
	at com.github.database.rider.core.configuration.DBUnitConfig.fromCustomGlobalFile(DBUnitConfig.java:116)
	at com.github.database.rider.core.configuration.GlobalConfig.createInstance(GlobalConfig.java:30)
```

Scenario:
1. Add `columnSensing` config to [sample-dbunit.yml](https://github.com/database-rider/database-rider/blob/master/rider-core/src/test/resources/config/sample-dbunit.yml)
```
columnSensing: true
```
2. Run [DBUnitConfigTest.java](https://github.com/database-rider/database-rider/blob/master/rider-core/src/test/java/com/github/database/rider/core/configuration/DBUnitConfigTest.java) test

Thanks for the nice work =)
ThDeng.

**Comment by rmpestano** [comment]
Hey @entireboy, thanks for the feedback and PR!
