### ISSUE TITLE
Add possibility to disable cycles check

### ISSUE THREAD

**Issue by lesterb** [database-rider/database-rider#386]
Suppose we have a database
```
CREATE TABLE parent {
    id number,
    selected_child_id number
}

CREATE TABLE children {
    id number,
    parent_id number
}
```
And we have entities

```
@Entity
public class Parent {
    @Id
    private int id;

    @OneToOne
    @JoinColumn(name="selected_child_id")
    private Child selectedForWhateverPurposeChild;
}

@Entity
public class Child {
    @Id
    private int id;

    @ManyToOne
    @JoinColumn(name="parent_id")
     private Parent parent;
}
```

Currently this will fail with 
`Caused by: org.dbunit.database.CyclicTablesDependencyException: Table: PARENT ([CHILD])
	at com.github.database.rider.core.api.dataset.RiderSequenceFilter$DependencyInfo.checkCycles(RiderSequenceFilter.java:285)
	at com.github.database.rider.core.api.dataset.RiderSequenceFilter.sortTableNames(RiderSequenceFilter.java:79)
`
and it's legitimate, but this prevents from the functionality of Child to be tested. Could you please add a flag, which disables this check or make disableConstraints also disable it as well?

**Comment by lesterb** [comment]
Well it appears that such property exists, and is called 'useSequenceFiltering = false'. Who could have guessed?

**Comment by lesterb** [comment]
Closed as not an issue
