### ISSUE TITLE
Caused by: org.dbunit.database.AmbiguousTableNameException:

### ISSUE THREAD

**Issue by estebangarciaalonso** [database-rider/database-rider#527]
I've migrated to SpringBoot 3, DbRider 1.35.0 and I'm trying to run tests and I'm getting this weird error

      @SpringBootTest(classes = { HibernateTestConfig.class, DaoTest_List_DBUnitConfig.class })
      @DBRider(dataSourceBeanName = "dbUnitDataSource")
      @DBUnit(schema = "test", qualifiedTableNames = true)
      @DataSet(CommonDbDomainUtils.DATA_TEST_FILE)
      public class XXXTest_List_DBUnit {
      
      }

I'm getting this error...

      Caused by: org.dbunit.database.AmbiguousTableNameException: XXX
	      at org.dbunit.dataset.OrderedTableNameMap.add(OrderedTableNameMap.java:198)
	      at org.dbunit.database.DatabaseDataSet.initialize(DatabaseDataSet.java:244)

The data is setup in a XML file.
The setup was working just fine with Springboot 2.6 and DbRider 1.13.1

I've tried:
* setting the schema
* using qualifiedTableNames 
* setting the data in the config, so it only runs once (if you can tell me how to run the data setup only once, it will be also appreciated)

**Comment by estebangarciaalonso** [comment]
I also tested with versions 1.34 and 1.33 and it is also happening with these versions....

**Comment by estebangarciaalonso** [comment]
There are 2 issues...
There is a problem if there is a dash (-) in the schema...
Also the new version requires extra config to make it work with MariaDB/MySQL...

@DBUnit(schema = "test", qualifiedTableNames=true, dataTypeFactoryClass = MySqlDataTypeFactory.class, metaDataHandler= MySqlMetadataHandler.class )

**Comment by rmpestano** [comment]
Hey @estebangarciaalonso, do you think we can improve this?  

> Also the new version requires extra config to make it work with MariaDB/MySQL...

This was not the case before? we had a fix related to Mysql connector in the[ last release](https://github.com/database-rider/database-rider/pull/528).

Let me know your thoughts
