### ISSUE TITLE
Class cast exception in IncludeReplacer for non string value

### ISSUE THREAD

**Issue by IvanPriests** [database-rider/database-rider#542]
If dataset contains non string values, IncludeReplacer will fail with like this :
```
Caused by: java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.String (java.lang.Integer and java.lang.String are in module java.base of loader 'bootstrap')
	at com.github.database.rider.core.replacers.IncludeReplacer.addReplacementsForTable(IncludeReplacer.java:36)
	at com.github.database.rider.core.replacers.IncludeReplacer.addReplacements(IncludeReplacer.java:24)
	at com.github.database.rider.core.dataset.DataSetExecutorImpl.performReplacements(DataSetExecutorImpl.java:461)
	at com.github.database.rider.core.dataset.DataSetExecutorImpl.createDataSet(DataSetExecutorImpl.java:129)
```

Template example:
```
example:
  - id: "312"
    external_id: "1"
    source: "test"
    max_send_attempts: 3
    subject: "test 1"
```

**Comment by IvanPriests** [comment]
applied [PR](https://github.com/database-rider/database-rider/pull/543)

**Comment by alanachtenberg** [comment]
@rmpestano Opened https://github.com/database-rider/database-rider/pull/627 please lmk if it needs any adjustments

**Comment by rmpestano** [comment]
Thank you @alanachtenberg, it looks good!
