### ISSUE TITLE
Multiple datasources not working in Spring Boot

### ISSUE THREAD

**Issue by alxxyz** [database-rider/database-rider#551]
We have multiple datasources in our Spring Boot application, and we get this error
```
org.springframework.beans.factory.NoUniqueBeanDefinitionException: No qualifying bean of type 'javax.sql.DataSource' available: expected single matching bean but found 2: firstDataSource,secondDataSource
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveNamedBean(DefaultListableBeanFactory.java:1273)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveBean(DefaultListableBeanFactory.java:494)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:349)
Suppressed: java.lang.NullPointerException: Cannot invoke "com.github.database.rider.core.RiderTestContext.getAnnotation(java.lang.Class)" because "riderTestContext" is null
		at com.github.database.rider.core.RiderRunner.exportDataSet(RiderRunner.java:113)
		at com.github.database.rider.core.RiderRunner.teardown(RiderRunner.java:67)
		at com.github.database.rider.spring.DBRiderTestExecutionListener.afterTestMethod(DBRiderTestExecutionListener.java:34)
		at org.springframework.test.context.TestContextManager.afterTestMethod(TestContextManager.java:445)
```
this is the test class
```
@RunWith(SpringRunner.class)
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@DBRider(dataSourceBeanName = "firstDataSource")
public class UserTest {
}
```
and the dependency
```
<dependency>
            <groupId>com.github.database-rider</groupId>
            <artifactId>rider-spring</artifactId>
            <version>1.35.0</version>
            <scope>test</scope>
        </dependency>
```

**Comment by rmpestano** [comment]
Hi @alxxyz, have you tried with rider-junit5? There's an [example here]( https://github.com/database-rider/database-rider/blob/master/rider-examples/spring-boot-dbunit-sample/src/test/java/com/github/database/rider/springboot/MultipleDataSourcesTest.java). I don't think we support multiple DS in rider-spring (cc @njuro @artemy-osipov  @yuriytkach)
