### ISSUE TITLE
Calling getString() without next() on a ResultSet in TableNameResolver#resolveSchema

### ISSUE THREAD

**Issue by Matrino** [database-rider/database-rider#571]
Hi.

I noticed an exception when trying to clean an Oracle Database.

Particularly while determining a schema, a ResultSet is being accessed without call to `next()` Method, which results in a java.sql.SQLException (ResultSet.next was not called), because initially the resultset is pointing to the -1 record.

Below I tried to identify the code that is causing the exception + stacktrace.

Thanks and keep up the good work.

https://github.com/database-rider/database-rider/blob/71b01fbd3f5fa39f8579d295c49ba2c0a86cbd79/rider-core/src/main/java/com/github/database/rider/core/util/TableNameResolver.java#L110

03 Okt 2023 12:17:03,795+02:00|WARN com.github.database.rider.core.util.TableNameResolver:resolveSchema - Can't resolve schema
java.sql.SQLException: ResultSet.next was not called
	at oracle.jdbc.driver.GeneratedScrollableResultSet.getString(GeneratedScrollableResultSet.java:374)
	at oracle.jdbc.driver.GeneratedResultSet.getString(GeneratedResultSet.java:596)
	**at com.github.database.rider.core.util.TableNameResolver.resolveSchema(TableNameResolver.java:110)**
	at com.github.database.rider.core.util.TableNameResolver.resolveSchema(TableNameResolver.java:79)
	at com.github.database.rider.core.dataset.DataSetExecutorImpl.handleConstraints(DataSetExecutorImpl.java:366)
	at com.github.database.rider.core.dataset.DataSetExecutorImpl.enableConstraints(DataSetExecutorImpl.java:339)
	at com.github.database.rider.core.dataset.DataSetExecutorImpl.clearDatabase(DataSetExecutorImpl.java:611)
	at com.github.database.rider.core.dataset.DataSetExecutorImpl.createDataSet(DataSetExecutorImpl.java:108)
	at com.github.database.rider.core.RiderRunner.runBeforeTest(RiderRunner.java:44)
	at com.github.database.rider.junit5.DBUnitExtension.beforeTestExecution(DBUnitExtension.java:69)

**Comment by Matrino** [comment]
Happens only when called from DataSetExecutorImpl#handleConstraints Method.
