### ISSUE TITLE
Expect not null in ExpectedDataSet using CONTAINS ?

### ISSUE THREAD

**Issue by netmikey** [database-rider/database-rider#588]
We use `CompareOperation.CONTAINS`. Is there an easy way to assert that a given field is `not null` in an expected DataSet? We don't know what data will be put in so we can't use an exact match, we just need to make sure the field isn't left empty.

For example: a process should set an "`activation_time`" field from `null` to the current time when it is executed.

As a bonus: if we could check that the field's value is, let's say within the last 5 minutes for example, this would be even better.

**Comment by rmpestano** [comment]
Have you checked [script assertions](https://github.com/database-rider/database-rider?tab=readme-ov-file#374-using-script-assertions-in-expected-datatset)? I think it can help in your scenario

**Comment by netmikey** [comment]
Yes, I tried using

```yml
mytable:
   - some: 1
     other: 2
     fields: 3
     activation_time: "js:(value != null)"
```

But I'm getting:

```
org.dbunit.dataset.datatype.TypeCastException: Unable to typecast value <js:(value != null)> of type <java.lang.String> to TIMESTAMP
	at org.dbunit.dataset.datatype.TimestampDataType.typeCast(TimestampDataType.java:138)
	at org.dbunit.dataset.datatype.AbstractDataType.compare(AbstractDataType.java:82)
	at com.github.database.rider.core.util.ContainsFilterTable.tableContains(ContainsFilterTable.java:127)
	at com.github.database.rider.core.util.ContainsFilterTable.setRows(ContainsFilterTable.java:88)
	at com.github.database.rider.core.util.ContainsFilterTable.<init>(ContainsFilterTable.java:57)
	at com.github.database.rider.core.dataset.DataSetExecutorImpl.compareClassic(DataSetExecutorImpl.java:868)
	at com.github.database.rider.core.dataset.DataSetExecutorImpl.compareCurrentDataSetWith(DataSetExecutorImpl.java:832)
	at com.github.database.rider.core.RiderRunner.performDataSetComparison(RiderRunner.java:144)
	at com.github.database.rider.core.RiderRunner.runAfterTest(RiderRunner.java:63)
	at com.github.database.rider.junit5.DBUnitExtension.afterTestExecution(DBUnitExtension.java:79)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: java.lang.IllegalArgumentException: Timestamp format must be yyyy-mm-dd hh:mm:ss[.fffffffff]
	at java.sql/java.sql.Timestamp.valueOf(Timestamp.java:224)
	at org.dbunit.dataset.datatype.TimestampDataType.typeCast(TimestampDataType.java:135)
	... 11 more
```

So I assumed script assertions weren't being evaluated in `CompareOperation.CONTAINS` mode?

**Comment by Pinkolik** [comment]
I have the same issue. Trying to assert timestamp field

**Comment by fhaala** [comment]
I have the exact same problem.

**Comment by welsh** [comment]
Same problem when using Contains:
```java
    @ExpectedDataSet(value = "expected/update.yml", compareOperation = CompareOperation.CONTAINS)
```
 I want to ensure a field was greater than a specific value:
```yml
session_log:
  - session_id: "11111111-1111-1111-1111-111111111111"
    seconds_in_session: "groovy:(value > 30)"
    created_time: "regex:.*"
```
And I get:
```
Caused by: org.dbunit.dataset.datatype.TypeCastException: Unable to typecast value <groovy:(value > 30)> of type <java.lang.String> to BIGINT
	at org.dbunit.dataset.datatype.BigIntegerDataType.typeCast(BigIntegerDataType.java:88)
	at org.dbunit.dataset.datatype.AbstractDataType.compare(AbstractDataType.java:82)
...
```
