### ISSUE TITLE
Do not rely on DatatypeConverter for Base64 conversion

### ISSUE THREAD

**Issue by netmikey** [database-rider/database-rider#590]
We're using Spring Boot 3 with Java 17.

When I try to export a DataSet that contains `byte[]` columns using this code:

```java
DataSetExporter.getInstance().export(
    connection, 
    new DataSetExportConfig().outputFileName("exported.yml"));
```

We get this stack trace:

```
java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
	at com.github.database.rider.core.dataset.writer.YMLWriter.row(YMLWriter.java:96)
	at org.dbunit.dataset.stream.DataSetProducerAdapter.produce(DataSetProducerAdapter.java:104)
	at com.github.database.rider.core.dataset.writer.YMLWriter.write(YMLWriter.java:117)
	at com.github.database.rider.core.exporter.DataSetExporter.export(DataSetExporter.java:144)
	at com.github.database.rider.core.exporter.DataSetExporter.export(DataSetExporter.java:71)
	at com.github.database.rider.core.exporter.DataSetExporter.export(DataSetExporter.java:67)
```

This is because most projects migrated away from `javax` API in favor of the `jakarta` equivalents. It looks like `YMLWriter` uses `DatatypeConverter` for Base64 conversion:

https://github.com/database-rider/database-rider/blob/3874d8d9e9699938f3fc6f12c6aedd3bb3d735d0/rider-core/src/main/java/com/github/database/rider/core/dataset/writer/YMLWriter.java#L96

Rider should probably prefer using the JDKs `java.util.Base64` class (available since Java 8) for this conversion. This would avoid relying on that old `javax` class.

**Comment by rmpestano** [comment]
Hey @netmikey, thanks for the feedback, would like to contribute that change?
