### ISSUE TITLE
Problem in using database-rider with JUnit5

### ISSUE THREAD

**Issue by paskaly** [database-rider/database-rider#78]
Hi Rafael,
and thanks for this very great job.
I wish to use it in an already existing project, wich is a REST ms. The goal is to use JUnit5, rest-assured and, of course, database-rider to simplify and to reach a more robust integration test system.
1. I use a `dbunit.yml` configuration file in `src/test/resource/` folder;
2. I createa an empty test class `RiderTest` as reported below.
3. After various errors I found (but in doc is well stated) that I have to declare a field of `ConnectionHolder` type. The field is initialized (correctly, as I seen in debugging)  with the field values of the above configuration file.
4. Neverthless, I continue to receive the following exception. With a surprise: the exception happens on the same object (I think) used in initializing the `connectionHolder`.

I don't know if I made some mistake, but ... may you help me?

Thanks,
Pasquale

```
java.lang.NullPointerException
	at com.github.database.rider.core.configuration.GlobalConfig.createInstance(GlobalConfig.java:33)
	at com.github.database.rider.core.configuration.GlobalConfig.instance(GlobalConfig.java:18)
	at com.github.database.rider.core.configuration.DBUnitConfig.fromGlobalConfig(DBUnitConfig.java:131)
	at com.github.database.rider.core.dataset.DataSetExecutorImpl.instance(DataSetExecutorImpl.java:84)
	at com.github.database.rider.junit5.DBUnitExtension.beforeTestExecution(DBUnitExtension.java:48)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$null$4(TestMethodTestDescriptor.java:138)
	at org.junit.jupiter.engine.execution.ThrowableCollector.execute(ThrowableCollector.java:40)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeBeforeMethodsOrCallbacksUntilExceptionOccurs(TestMethodTestDescriptor.java:152)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeBeforeTestExecutionCallbacks(TestMethodTestDescriptor.java:137)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:108)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.lambda$execute$3(HierarchicalTestExecutor.java:83)
	at org.junit.platform.engine.support.hierarchical.SingleTestExecutor.executeSafely(SingleTestExecutor.java:66)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:77)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.lambda$null$2(HierarchicalTestExecutor.java:92)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.lambda$execute$3(HierarchicalTestExecutor.java:92)
	at org.junit.platform.engine.support.hierarchical.SingleTestExecutor.executeSafely(SingleTestExecutor.java:66)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:77)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.lambda$null$2(HierarchicalTestExecutor.java:92)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.lambda$execute$3(HierarchicalTestExecutor.java:92)
	at org.junit.platform.engine.support.hierarchical.SingleTestExecutor.executeSafely(SingleTestExecutor.java:66)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:77)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:51)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:43)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:170)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:154)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:90)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:74)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	Suppressed: java.lang.NullPointerException
		at com.github.database.rider.junit5.DBUnitExtension.afterTestExecution(DBUnitExtension.java:72)
		at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$null$7(TestMethodTestDescriptor.java:201)
		at org.junit.jupiter.engine.execution.ThrowableCollector.execute(ThrowableCollector.java:40)
		at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeAllAfterMethodsOrCallbacks$13(TestMethodTestDescriptor.java:226)
		at java.util.ArrayList.forEach(ArrayList.java:1257)
		at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeAllAfterMethodsOrCallbacks(TestMethodTestDescriptor.java:224)
		at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeAfterTestExecutionCallbacks(TestMethodTestDescriptor.java:200)
		at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:112)
		... 41 more
```

 
```java
@ExtendWith(DBUnitExtension.class)
@RunWith(JUnitPlatform.class)
@DataSet(value = "dataset/dataset.xml", cleanBefore = false, strategy = SeedStrategy.UPDATE)
@DisplayName("Test for /GET ")
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
public class RiderTest  {

    private ConnectionHolder connectionHolder =  new ConnectionHolder() {
        @Override
        public Connection getConnection() throws SQLException {
            ConnectionConfig c = DBUnitConfig.fromGlobalConfig().getConnectionConfig();
            String dbUrl =  c.getUrl();
            String dbUserName = c.getUser();
            String dbPassword = c.getPassword();
            Connection cn = null;
            try {
                Class.forName(c.getDriver());
                cn = DriverManager.getConnection(dbUrl,dbUserName, dbPassword);
            } catch (ClassNotFoundException e) {
                e.printStackTrace();
                return (null);
            }
            System.out.println(cn.toString());
            return (cn);
        }
    };


    /**
     * GET /Param
     */
    @DBRider
    // This is just one more try ...
    @DataSet(value = "dataset/dataset.xml", cleanBefore = false, strategy = SeedStrategy.UPDATE)
    @DisplayName("GET /Param")
    public void checkParamGet() {
        assert(true);
    }
}
```

**Comment by paskaly** [comment]
(UPDATE)
After some attempt, found the cause:
the problema arises from an improper setting in `dbunit.yml`. In detail: _the `escapePattern:` was without any value..._
```yml
  escapePattern:
```
